#!/bin/bash
# Build script for VoiceCapture macOS app

set -e  # Exit on error

echo "=========================================="
echo "Building VoiceCapture macOS App"
echo "=========================================="
echo ""

# Check for uncommitted changes
echo "🔍 Checking git status..."
if ! git diff-index --quiet HEAD --; then
    echo "❌ Error: There are uncommitted changes in the repository."
    echo ""
    echo "Please commit all changes before building:"
    echo "  git status"
    echo "  git add <files>"
    echo "  git commit -m \"your message\""
    echo ""
    exit 1
fi
echo "✅ All changes committed"
echo ""

# Generate version information
echo "📝 Generating version information..."
GIT_COMMIT=$(git rev-parse HEAD)
GIT_COMMIT_SHORT=$(git rev-parse --short HEAD)
GIT_DATE=$(git log -1 --format=%cd --date=short)
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

# Create version.py with git info
cat > version.py << EOF
"""
Version information for VoiceCapture
This file is automatically generated during the build process
"""

# Git version information
VERSION_COMMIT = "$GIT_COMMIT"
VERSION_COMMIT_SHORT = "$GIT_COMMIT_SHORT"
VERSION_DATE = "$GIT_DATE"
VERSION_BRANCH = "$GIT_BRANCH"
VERSION_DIRTY = False

def get_version_info():
    """Get formatted version information"""
    if VERSION_DIRTY:
        status = " (uncommitted changes)"
    else:
        status = ""

    return {
        'commit': VERSION_COMMIT,
        'commit_short': VERSION_COMMIT_SHORT,
        'date': VERSION_DATE,
        'branch': VERSION_BRANCH,
        'dirty': VERSION_DIRTY,
        'display': f"{VERSION_COMMIT_SHORT} ({VERSION_DATE}){status}"
    }

def get_version_string():
    """Get a single-line version string"""
    info = get_version_info()
    return f"VoiceCapture v{info['display']}\\nBranch: {info['branch']}\\nCommit: {info['commit']}"
EOF

echo "✅ Version: $GIT_COMMIT_SHORT ($GIT_DATE) on branch $GIT_BRANCH"
echo ""

# Check if PyInstaller is installed
if ! command -v pyinstaller &> /dev/null; then
    echo "❌ PyInstaller not found. Installing..."
    pip install pyinstaller
fi

# Check if ffmpeg is available
if ! command -v ffmpeg &> /dev/null; then
    echo "❌ ffmpeg not found. Please install it first:"
    echo "   brew install ffmpeg"
    exit 1
fi

echo "✅ ffmpeg found at: $(which ffmpeg)"
echo ""

# Clean previous builds
echo "🧹 Cleaning previous builds..."
rm -rf build/ dist/
echo ""

# Build the app
echo "🔨 Building app with PyInstaller..."
pyinstaller voice_capture.spec --clean --noconfirm
echo ""

# Check if build was successful
if [ -d "dist/VoiceCapture.app" ]; then
    echo "=========================================="
    echo "✅ Build successful!"
    echo "=========================================="
    echo ""
    echo "App location: dist/VoiceCapture.app"
    echo ""
    echo "To install:"
    echo "  1. Direct run:      open dist/VoiceCapture.app"
    echo "  2. Install to apps: cp -r dist/VoiceCapture.app /Applications/"
    echo ""
    echo "To test from command line:"
    echo "  ./dist/VoiceCapture.app/Contents/MacOS/VoiceCapture"
    echo ""
else
    echo "=========================================="
    echo "❌ Build failed!"
    echo "=========================================="
    exit 1
fi
