@echo off
REM Build script for VoiceCapture Windows app
REM This script builds the Windows executable using PyInstaller

echo ============================================================
echo Building VoiceCapture Windows App
echo ============================================================
echo.

REM Check if virtual environment is activated
where python >nul 2>nul
if %ERRORLEVEL% neq 0 (
    echo ERROR: Python not found in PATH
    echo Please activate your virtual environment first:
    echo   env\Scripts\activate
    exit /b 1
)

REM Check for uncommitted changes
echo Checking git status...
git diff-index --quiet HEAD -- >nul 2>nul
if %ERRORLEVEL% neq 0 (
    echo   [ERROR] There are uncommitted changes in the repository.
    echo.
    echo Please commit all changes before building:
    echo   git status
    echo   git add ^<files^>
    echo   git commit -m "your message"
    echo.
    exit /b 1
)
echo   [OK] All changes committed
echo.

REM Generate version information
echo Generating version information...
for /f "delims=" %%i in ('git rev-parse HEAD') do set GIT_COMMIT=%%i
for /f "delims=" %%i in ('git rev-parse --short HEAD') do set GIT_COMMIT_SHORT=%%i
for /f "delims=" %%i in ('git log -1 --format^=%%cd --date^=short') do set GIT_DATE=%%i
for /f "delims=" %%i in ('git rev-parse --abbrev-ref HEAD') do set GIT_BRANCH=%%i

REM Create version.py with git info
echo """Version information for VoiceCapture""" > version.py
echo This file is automatically generated during the build process >> version.py
echo """ >> version.py
echo. >> version.py
echo # Git version information >> version.py
echo VERSION_COMMIT = "%GIT_COMMIT%" >> version.py
echo VERSION_COMMIT_SHORT = "%GIT_COMMIT_SHORT%" >> version.py
echo VERSION_DATE = "%GIT_DATE%" >> version.py
echo VERSION_BRANCH = "%GIT_BRANCH%" >> version.py
echo VERSION_DIRTY = False >> version.py
echo. >> version.py
echo def get_version_info(): >> version.py
echo     """Get formatted version information""" >> version.py
echo     if VERSION_DIRTY: >> version.py
echo         status = " (uncommitted changes)" >> version.py
echo     else: >> version.py
echo         status = "" >> version.py
echo. >> version.py
echo     return { >> version.py
echo         'commit': VERSION_COMMIT, >> version.py
echo         'commit_short': VERSION_COMMIT_SHORT, >> version.py
echo         'date': VERSION_DATE, >> version.py
echo         'branch': VERSION_BRANCH, >> version.py
echo         'dirty': VERSION_DIRTY, >> version.py
echo         'display': f"{VERSION_COMMIT_SHORT} ({VERSION_DATE}){status}" >> version.py
echo     } >> version.py
echo. >> version.py
echo def get_version_string(): >> version.py
echo     """Get a single-line version string""" >> version.py
echo     info = get_version_info() >> version.py
echo     return f"VoiceCapture v{info['display']}\nBranch: {info['branch']}\nCommit: {info['commit']}" >> version.py

echo   [OK] Version: %GIT_COMMIT_SHORT% (%GIT_DATE%) on branch %GIT_BRANCH%
echo.

REM Check if PyInstaller is installed
python -c "import PyInstaller" >nul 2>nul
if %ERRORLEVEL% neq 0 (
    echo ERROR: PyInstaller not found
    echo Installing PyInstaller...
    pip install pyinstaller
)

echo Step 1: Checking for FFmpeg...
if not exist ffmpeg_windows\ffmpeg.exe (
    echo FFmpeg not found, downloading...
    python download_ffmpeg_windows.py
    if %ERRORLEVEL% neq 0 (
        echo   [WARNING] FFmpeg download failed
        echo   App will be built without bundled FFmpeg
        echo   Users will need to install FFmpeg separately
        timeout /t 3 >nul
    )
) else (
    echo   [OK] FFmpeg found at ffmpeg_windows\ffmpeg.exe
)
echo.

echo Step 2: Cleaning previous build...
if exist build rmdir /s /q build
if exist dist\VoiceCapture rmdir /s /q dist\VoiceCapture
echo   [OK] Cleaned build directories
echo.

echo Step 3: Building executable with PyInstaller...
pyinstaller --noconfirm voice_capture_windows.spec
if %ERRORLEVEL% neq 0 (
    echo   [ERROR] Build failed!
    exit /b 1
)
echo   [OK] Build completed
echo.

echo ============================================================
echo Build Summary
echo ============================================================
echo Executable location: dist\VoiceCapture\VoiceCapture.exe
echo.
echo To run the app:
echo   dist\VoiceCapture\VoiceCapture.exe
echo.
echo To create an installer:
echo   Run build_installer.bat (requires Inno Setup)
echo ============================================================
